# Generated by Django 4.1.4 on 2023-02-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
